import type { Metadata } from "next";

import { getServerSession } from "next-auth";
import { authOptions } from "../api/auth/[...nextauth]/options";
import { redirect } from "next/navigation";


export const metadata: Metadata = {
  title: "Silk Eye - Ковер мечты",
  description: "Generated by create next app",
};

export default async function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await getServerSession(authOptions)
  if(session) {
    redirect('/user')
  }

  return (
    <main
      className="mx-[290rem] rounded-[10rem] mt-[86rem] p-[40rem]"
      style={{ border: "2rem solid #ffffff" }}
    >
      
      {children}
    </main>
  );
}
