import type { Metadata } from "next";

import "@/styles/reset.scss";
import "@/styles/global.scss";

import Navbar from "@/components/navbar";
import dynamic from "next/dynamic";

const CartContextProvider = dynamic(
  () => import("@/lib/contexts/cartContext"),
  { ssr: false }
);

export const metadata: Metadata = {
  title: "Silk Eye - Ковер мечты",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <CartContextProvider>
          <div className="wrapper">
            <Navbar />
            {children}
          </div>
        </CartContextProvider>
      </body>
    </html>
  );
}
